spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: uplus-elasticcache.fhxyu0.ng.0001.apn2.cache.amazonaws.com
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB #1GB
      max-request-size: 1000MB # 1GB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      group-id: video-transcoding-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: video-transcoding

s3:
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
  buckets:
    source: ${S3_BUCKET_NAME}
    resize: ${S3_RESIZE_BUCKET_NAME}

kakao:
  client-id: ${KAKAO_REST_API_KEY}
  redirect-uri: https://mungtivity.vercel.app/login
  client-secret: ${KAKAO_CLIENT_SECRET}

jwt:
  token:
    secretKey: ${JWT_SECRET}

weather:
  encoding-key: ${WEATHER_KEY}

aes:
  key: ${AES_KEY}

ffmpeg:
  path: /usr/bin/ffmpeg
ffprobe:
  path: /usr/bin/ffprobe

slack:
  webhook:
    url: https://hooks.slack.com/services/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